name: Create pull_request
on:
  schedule:
    - cron: "5 2 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: create now
        id: date
        run: |
          echo "now=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
          echo "date=$(date '+%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: create diff
        run: echo "runned at $(date +'%Y-%m-%d %H:%M:%S')" >> diff.txt
      - name: create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "test-action-flow ${{ steps.date.outputs.now }}"
          body: "test-action-flow"
          branch: "auto/${{ steps.date.outputs.date }}"
          commit-message: "chore: create pull request ${{ steps.date.outputs.now }}"
          delete-branch: true
